// API service for HeartCheck AI
// This simulates API calls to a backend service for AI analysis

// Types for conversation analysis
export interface VibeAnalysis {
  vibe: string;
  intentions: string;
  flags: string;
  nextMove: string;
}

export interface IntentAnalysis {
  interestScore: number;
  gameLevel: string;
  breakdown: string;
  signals: string;
}

export interface PatternAnalysis {
  pattern: string;
  description: string;
  impact: number;
  why: string;
  solution: string;
}

export interface TarotReading {
  cards: {
    present: {
      name: string;
      meaning: string;
    };
    hidden: {
      name: string;
      meaning: string;
    };
    future: {
      name: string;
      meaning: string;
    };
  };
  summary: string;
}

// Dictionary of predefined responses for different scenarios
// In a real app, these would be generated by an AI model
const vibeDictionary = [
  {
    keywords: ["not texting", "ghosted", "left on read", "no response"],
    response: {
      vibe: "You're dealing with classic ghosting energy. 👻 The inconsistent responses and sudden disappearance show emotional unavailability.",
      intentions:
        "They're keeping options open while avoiding direct communication. This often means they're either conflict-avoidant or just not that invested.",
      flags:
        "🚩 Disappearing without explanation\n🚩 Hot and cold behavior\n🚩 Vague about plans\n✅ Was engaged in conversation initially",
      nextMove:
        "Focus on people who match your energy, bestie! This ghosting says more about them than you. Your time is valuable - don't waste it waiting for someone who doesn't make you a priority. 💅",
    },
  },
  {
    keywords: [
      "flirting",
      "compliments",
      "called me cute",
      "said i was pretty",
      "thinks im hot",
    ],
    response: {
      vibe: "The flirty energy is overflowing here! 💖 They're definitely giving interested vibes with those compliments and attention to detail.",
      intentions:
        "Their intentions seem genuine - they're putting effort into creating a connection and making it clear they find you attractive.",
      flags:
        "✅ Consistent communication\n✅ Shows interest in your life\n✅ Compliments are respectful\n🚩 Watch if compliments are all physical",
      nextMove:
        "The vibe check is good! If you're interested too, match their energy with some flirty but authentic responses. Make sure it moves beyond just physical compliments to establish a real connection. 💕",
    },
  },
  {
    keywords: ["mixed signals", "confusing", "hot and cold", "unsure"],
    response: {
      vibe: "You're on the mixed signals rollercoaster. 🎢 They're giving both interested and distant energy, which creates confusion and uncertainty.",
      intentions:
        "They likely enjoy your attention but aren't fully committed to pursuing something serious. This could be emotional immaturity or indecision.",
      flags:
        "🚩 Inconsistent communication patterns\n🚩 Actions don't match their words\n🚩 Makes plans but often cancels\n✅ Shows genuine moments of connection",
      nextMove:
        "Set clear boundaries and communicate what you need. If the mixed signals continue, consider whether this emotional rollercoaster is worth the ride. Remember, confusion is not the same as mystery - you deserve clarity! ✨",
    },
  },
  {
    keywords: [
      "new relationship",
      "just started dating",
      "first date",
      "beginning",
    ],
    response: {
      vibe: "There's fresh relationship energy here! ✨ The excitement and curiosity between you two is palpable in your communications.",
      intentions:
        "They seem genuinely interested in getting to know you better. The questions and engagement show investment in building something.",
      flags:
        "✅ Makes consistent effort to communicate\n✅ Asks thoughtful questions\n✅ Respects boundaries\n🚩 Watch for love bombing or rushing",
      nextMove:
        "Enjoy this discovery phase! Keep the communication open and honest, and don't rush the process. Pay attention to how they respond to different sides of your personality as you reveal more of yourself. 🦋",
    },
  },
  {
    keywords: ["ex", "broke up", "back together", "trying again"],
    response: {
      vibe: "There's lingering attachment energy with complex emotions. 🔄 The history between you creates both familiarity and caution.",
      intentions:
        "Their intentions seem mixed between nostalgia for what was good and uncertainty about whether things can actually be different.",
      flags:
        "🚩 Same patterns may still exist\n🚩 Unresolved issues from before\n✅ Familiar comfort and understanding\n✅ Shared history can build depth",
      nextMove:
        "Before diving back in, have an honest conversation about what's changed since the breakup. Don't ignore the reasons things ended before. If you decide to try again, set clear boundaries and watch for old patterns returning. Growth requires both people to have evolved! 🌱",
    },
  },
];

const intentDictionary = [
  {
    keywords: ["not interested", "rejecting", "friendzone"],
    response: {
      interestScore: 25,
      gameLevel: "💀 dead end",
      breakdown:
        "The signs point to low romantic interest. The delayed responses, lack of questions about your life, and absence of flirty energy suggest they see this as platonic.",
      signals:
        "Watch for deflection when you suggest meeting up, changing the subject when conversations get personal, or consistently taking hours to respond to your messages.",
    },
  },
  {
    keywords: ["crushing", "likes me", "into me", "interested"],
    response: {
      interestScore: 85,
      gameLevel: "🧠 smart flirt",
      breakdown:
        "They're definitely showing strong interest! The consistent communication, thoughtful questions, and subtle flirting all point to genuine attraction.",
      signals:
        "Notice how they remember small details about you, find reasons to talk to you, and their messages have a playful, warm energy. These are all green flags!",
    },
  },
  {
    keywords: ["breadcrumbing", "mixed signals", "confusing"],
    response: {
      interestScore: 45,
      gameLevel: "🧩 mixed",
      breakdown:
        "They're showing just enough interest to keep you engaged, but not committing fully. This often happens when someone likes the attention but isn't sure about their feelings.",
      signals:
        "Watch for inconsistent patterns - they'll disappear then return with extra affection, make vague future plans without setting dates, or be very engaged then suddenly distant.",
    },
  },
  {
    keywords: ["busy", "slow responses", "work"],
    response: {
      interestScore: 60,
      gameLevel: "🧠 smart flirt",
      breakdown:
        "There seems to be genuine interest, but with competing priorities. When they do engage, the quality suggests they care, even if the quantity is inconsistent.",
      signals:
        "Look for apologetic messages after delays, detailed responses even if they're not frequent, and efforts to make real plans despite their schedule.",
    },
  },
  {
    keywords: ["dating app", "matched", "tinder", "bumble", "hinge"],
    response: {
      interestScore: 70,
      gameLevel: "🧩 mixed",
      breakdown:
        "The initial interest is definitely there - matching and maintaining conversation shows potential. However, dating app dynamics often include talking to multiple people.",
      signals:
        "Pay attention to whether they ask questions to get to know you deeper, suggest moving from the app to texting, and most importantly, make efforts to meet in person.",
    },
  },
];

// Simulate AI analysis with predefined responses based on keywords
export const analyzeConversation = async (
  conversation: string
): Promise<VibeAnalysis> => {
  // Simulate API delay
  await new Promise((resolve) => setTimeout(resolve, 1500));

  // Convert to lowercase for matching
  const text = conversation.toLowerCase();

  // Find matching keyword set
  const match = vibeDictionary.find((entry) =>
    entry.keywords.some((keyword) => text.includes(keyword))
  );

  // Return matching response or default
  return (
    match?.response || {
      vibe: "This conversation has an intriguing energy. There's a mix of engagement and some hesitation that makes it hard to fully decode.",
      intentions:
        "Their intentions seem neutral - they're responding and keeping the conversation going, but not necessarily pushing for more or pulling back.",
      flags:
        "✅ Basic communication etiquette\n🚩 Not asking many questions\n✅ Responds within reasonable time\n🚩 Keeps things somewhat surface-level",
      nextMove:
        "Try adding more depth to your conversations to see how they respond. Ask thoughtful questions and see if they match your energy. Their reaction will tell you a lot about their interest level! ✨",
    }
  );
};

export const analyzeIntent = async (
  conversation: string
): Promise<IntentAnalysis> => {
  // Simulate API delay
  await new Promise((resolve) => setTimeout(resolve, 1800));

  // Convert to lowercase for matching
  const text = conversation.toLowerCase();

  // Find matching keyword set
  const match = intentDictionary.find((entry) =>
    entry.keywords.some((keyword) => text.includes(keyword))
  );

  // Return matching response or default
  return (
    match?.response || {
      interestScore: 55,
      gameLevel: "🧩 mixed",
      breakdown:
        "Based on the conversation, there's moderate interest. They engage with your messages but might not be fully invested yet. The connection is developing but still uncertain.",
      signals:
        "Look for increasing engagement over time, more personal questions, and whether they initiate conversations or just respond. Their consistency will be a key indicator of real interest.",
    }
  );
};

// Generate pattern analysis
export const analyzePattern = async (
  answers: Record<string, string>
): Promise<PatternAnalysis> => {
  // Simulate API delay
  await new Promise((resolve) => setTimeout(resolve, 2000));

  // Logic to determine pattern based on answers
  // In a real app, this would use ML to identify patterns
  let pattern = "";
  let description = "";
  let why = "";
  let solution = "";

  if (
    answers.q1 === "always" &&
    (answers.q3 === "suspicious" || answers.q3 === "retreat")
  ) {
    pattern = "Unavailable Attraction Pattern";
    description =
      "You're consistently drawn to emotionally unavailable people.";
    why =
      "This often stems from early attachment patterns. The unpredictable nature of these connections triggers the reward centers in your brain, creating an addiction-like attraction to the emotional rollercoaster.";
    solution =
      "Start recognizing the early signs of emotional unavailability. Practice sitting with the discomfort of walking away from intense chemistry when red flags appear. Consider what 'safety' means in a relationship and how it might actually feel unfamiliar to you.";
  } else if (answers.q4 === "trust" && answers.q2 === "often") {
    pattern = "Trust Sabotage Loop";
    description = "Past trust issues keep affecting your new relationships.";
    why =
      "When we've been hurt before, our brain creates protective mechanisms to prevent future pain. This hypervigilance makes you spot potential betrayal everywhere, sometimes creating a self-fulfilling prophecy.";
    solution =
      "Work on separating past hurts from current relationships. Practice giving people the benefit of the doubt while still maintaining healthy boundaries. Consider journaling about the difference between intuition and fear.";
  } else if (answers.q3 === "retreat" && answers.q5 === "veryShort") {
    pattern = "Fear of Commitment Cycle";
    description = "You tend to pull away when things get serious.";
    why =
      "This often relates to a fear of losing independence or being vulnerable. The initial stages feel exciting and safe, but deeper intimacy triggers anxiety about potential loss or disappointment.";
    solution =
      "Try to identify exactly when the urge to run appears. What emotions come up in that moment? Practice sitting with the discomfort rather than acting on it immediately. Small steps of vulnerability can help rewire these patterns.";
  } else if (answers.q4 === "communication" && answers.q2 === "often") {
    pattern = "Communication Breakdown Pattern";
    description = "You struggle with expressing needs in relationships.";
    why =
      "You might have learned early that voicing needs led to conflict or disappointment. This creates a pattern of silent expectations and eventual resentment when those unspoken needs aren't met.";
    solution =
      "Practice articulating small needs first in low-stakes situations. Remember that mind-reading isn't a realistic expectation in relationships. Healthy partners welcome knowing how to support you better.";
  } else {
    pattern = "Mixed Pattern";
    description =
      "You have some recurring themes but not one dominant pattern.";
    why =
      "Your relationship dynamics show flexibility and variation, which can be healthy! However, there are some recurring themes that might be worth exploring further.";
    solution =
      "Continue developing self-awareness by journaling about your emotional responses in relationships. Notice which situations trigger strongest reactions, as these often connect to deeper patterns.";
  }

  return {
    pattern,
    description,
    impact: Math.floor(Math.random() * 30) + 70, // 70-100
    why,
    solution,
  };
};

// Generate tarot reading based on situation
export const generateTarotReading = async (
  situation: string
): Promise<TarotReading> => {
  // Simulate API delay
  await new Promise((resolve) => setTimeout(resolve, 2200));

  // Generate tarot reading (in a real app, this would use a more sophisticated algorithm)
  const tarotCards = [
    {
      name: "The Lovers",
      meanings: [
        "There's a strong connection between you two. The chemistry is undeniable, but this card asks if it's just passion or something deeper.",
        "One of you may be idealizing the other or the relationship. There might be a choice that needs to be made soon.",
        "This connection has potential for something meaningful if you can move beyond the surface attraction to real intimacy.",
      ],
    },
    {
      name: "The Hermit",
      meanings: [
        "They're in a period of self-reflection right now. Their distant behavior isn't about you—they're trying to figure themselves out.",
        "They may be afraid of getting hurt, so they're pulling back to protect themselves. There's wisdom in this caution.",
        "After this introspection, they'll emerge with clearer intentions. Patience now could lead to a deeper connection later.",
      ],
    },
    {
      name: "The Tower",
      meanings: [
        "There's sudden change or disruption in this connection. What seemed stable might be shaken to its core.",
        "The foundation wasn't as solid as you thought. This upheaval is revealing truth that was always there beneath the surface.",
        "After destruction comes rebuilding. This clearing of illusions can lead to something more authentic, but only if you're both willing to start fresh.",
      ],
    },
    {
      name: "The Fool",
      meanings: [
        "You're at the beginning of something new and exciting. There's innocence and spontaneity in this connection.",
        "There may be naivety here—one or both of you might not be seeing potential pitfalls. Trust your intuition.",
        "This relationship has the freedom to evolve in many directions. Stay open to possibilities rather than forcing a specific outcome.",
      ],
    },
    {
      name: "The Moon",
      meanings: [
        "Things aren't as they appear. There's confusion or illusion clouding this situation, making it hard to see clearly.",
        "Unconscious patterns or fears are affecting how you relate to each other. What's triggering you might be from your past.",
        "As the moon waxes and wanes, so will this connection. Clarity will come, but you must first navigate through the shadows.",
      ],
    },
    {
      name: "The Star",
      meanings: [
        "There's hope and inspiration in this connection. After difficult times, this relationship feels like a renewal.",
        "This person sees a special quality in you that others might miss. There's a spiritual dimension to your connection.",
        "Follow this gentle light. This relationship has healing potential that can guide you both toward greater authenticity.",
      ],
    },
    {
      name: "The Empress",
      meanings: [
        "There's nurturing energy between you. This connection feels emotionally abundant and fertile with possibilities.",
        "One of you may be giving more than receiving. Remember that true nurturing includes self-care too.",
        "This relationship has the potential to help both of you flourish and grow if you maintain a balance of giving and receiving.",
      ],
    },
  ];

  // Randomly select three different cards
  const shuffledCards = [...tarotCards].sort(() => 0.5 - Math.random());
  const present = shuffledCards[0];
  const hidden = shuffledCards[1];
  const future = shuffledCards[2];

  // Generate a custom summary based on the cards and situation
  let summary = `The cards have spoken about your situation: "${situation.substring(
    0,
    30
  )}..."`;

  if (present.name === "The Tower" || present.name === "The Moon") {
    summary += " You're in a period of significant change or uncertainty.";
  } else {
    summary += " There's meaningful energy surrounding you right now.";
  }

  if (hidden.name === "The Star" || hidden.name === "The Empress") {
    summary +=
      " What's hidden beneath the surface suggests more hope and nurturing than you realize.";
  } else {
    summary +=
      " There are deeper currents affecting this connection that aren't immediately visible.";
  }

  if (future.name === "The Lovers" || future.name === "The Star") {
    summary +=
      " The future holds potential for growth and deeper connection if you remain open to its guidance.";
  } else {
    summary +=
      " Moving forward will require navigating with awareness and an open heart.";
  }

  return {
    cards: {
      present: {
        name: present.name,
        meaning: present.meanings[0],
      },
      hidden: {
        name: hidden.name,
        meaning: hidden.meanings[1],
      },
      future: {
        name: future.name,
        meaning: future.meanings[2],
      },
    },
    summary,
  };
};
