// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hysgdyufvyojwdikuglt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh5c2dkeXVmdnlvandkaWt1Z2x0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzODgzNjAsImV4cCI6MjA2MDk2NDM2MH0.Bp8dXit1ZFmxMutkIg4Gcmd6fS_lTXFBiv0D22_W18Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);